# Generated by Django 2.2.1 on 2019-06-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_restrict_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moreimages',
            old_name='description',
            new_name='img_description',
        ),
    ]
