# Generated by Django 2.2.1 on 2019-06-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190623_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moreimages',
            old_name='img_description',
            new_name='description',
        ),
    ]
