# Generated by Django 2.2.1 on 2019-07-10 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_auto_20190703_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdf_files')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('computer science', 'Computer Science'), ('mathematics', 'Mathematics')], max_length=150)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300')], max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
