# Generated by Django 2.2.1 on 2019-07-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DurationField(verbose_name='Starting at')),
                ('end', models.DurationField(verbose_name='Ending at')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Wednesday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=150)),
                ('courses', models.ManyToManyField(to='blog.Course')),
            ],
        ),
    ]
