# Generated by Django 2.2.1 on 2019-07-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_course_day_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='time',
            name='start',
            field=models.DateTimeField(verbose_name='Starting at'),
        ),
    ]
