# Generated by Django 2.2.1 on 2019-07-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190713_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='start',
            field=models.DurationField(verbose_name='Starting at'),
        ),
    ]
