# Generated by Django 2.2.1 on 2019-07-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190713_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end',
            field=models.DurationField(verbose_name='Ending at'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.DurationField(verbose_name='Starting at'),
        ),
    ]
