# Generated by Django 2.2.1 on 2019-07-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190713_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_file',
            name='is_mybook',
            field=models.BooleanField(default=False),
        ),
    ]
