# Generated by Django 2.2.1 on 2019-07-13 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_pdf_file_is_mybook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_file',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
