# Generated by Django 2.2.1 on 2019-06-25 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('computer science', 'Computer Science'), ('mathematics', 'Mathematics')], max_length=255)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300')], max_length=10)),
                ('membership', models.CharField(choices=[('student', 'Student'), ('representative', 'Representative')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
