# Generated by Django 2.2.1 on 2019-07-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile_pic'),
        ),
    ]
